// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    Temp: typeof import('./src/components/draft/Temp.vue')['default']
    TestApi: typeof import('./src/components/TestApi.vue')['default']
  }
}
