// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import("@arco-design/web-vue")["Button"]
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    NavTd: typeof import('./src/components/common/Nav/Nav-td.vue')['default']
    PathInput: typeof import('./src/components/common/Nav/helpers/PathInput.vue')['default']
    QuestionSquare: typeof import('./src/components/draft/QuestionSquare.vue')['default']
    Temp: typeof import("./src/components/draft/QuestionSquare.vue")["default"]
    TestApi: typeof import("./src/components/TestApi.vue")["default"]
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
    TestTemplate: typeof import('./src/components/draft/TestTemplate.vue')['default']
  }
}
