// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import("@arco-design/web-vue")["Button"]
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    NavTd: typeof import('./src/components/common/Nav/Nav-td.vue')['default']
    OdinFooter: typeof import('./src/components/common/Footer/OdinFooter.vue')['default']
    PathInput: typeof import('./src/components/common/Nav/helpers/PathInput.vue')['default']
    QuestionSquare: typeof import('./src/components/draft/QuestionSquare.vue')['default']
    Temp: typeof import("./src/components/draft/QuestionSquare.vue")["default"]
    TestApi: typeof import("./src/components/TestApi.vue")["default"]
    TestCarousel: typeof import('./src/components/test/TestCarousel.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
    TestDraggle: typeof import('./src/components/test/TestDraggle.vue')['default']
    TestTemplate: typeof import('./src/components/draft/TestTemplate.vue')['default']
    TestUpload: typeof import('./src/components/test/TestUpload.vue')['default']
    Validator: typeof import('./src/components/common/service/Validator.vue')['default']
  }
}
