// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    InnerSearch: typeof import('./src/components/InnerSearch.vue')['default']
    NavTdVue: typeof import('./src/components/nav-td/NavTdVue.vue')['default']
  }
}
